GET http://localhost:2000/

###
POST http://localhost:2000/api

###
GET http://localhost:2000/user

### Save a url

POST http://localhost:2000/url/E-0PPtfubqq2C_dKLyTz2
Content-Type: application/json

###
POST http://localhost:2000/user
Content-Type: application/json

{
    "name": "Daniel",
    "lastName": "Sepulveda",
    "email": "dsepulveda@gmail.com"
}

###
DELETE  http://localhost:2000/user/YAsj8CEbeGnwiJVn-onL5

###
PATCH  http://localhost:2000/user/Na4FySpWZSSSHKdTxPh-r
Content-Type: application/json

{
"name": "Sebassss"
}

###
// ----------------------------------------------------
GET http://localhost:2000/

###
POST http://localhost:2000/api

###
GET http://localhost:2000/article

###
POST http://localhost:2000/article
Content-Type: application/json

{
    "name": "Seba",
    "email": "sparra@gmail.com"
}

###
DELETE  http://localhost:2000/article/t3NGycPxLgDW28VgLqIx0

###
PATCH  http://localhost:2000/article/M2iIxanrP9PvlNIFCP3Cg
Content-Type: application/json

{
"name": "PEPITO"
    
}
### Save a url
POST http://localhost:2000/url
Content-Type: application/json

{
    "link": "http://www.google.com"
}