GET http://localhost:2000/

### get all users
GET http://localhost:2000/api/user

### get one user
GET http://localhost:2000/api/user/x

### Save a url

POST http://localhost:2000/api/url/asasa
Content-Type: application/json

###
POST http://localhost:2000/api/user
Content-Type: application/json

{
    "name": "Mario",
    "lastName": "Zarricueta",
    "email": "z"
}

### DELETE USER BY ID
DELETE  http://localhost:2000/api/user/5oeEwmhbRR4B3H3AiXetC

###
PATCH  http://localhost:2000/api/user/Na4FySpWZSSSHKdTdsds
Content-Type: application/json

{
"email": "asads"
}

###
// ----------------------------------------------------
GET http://localhost:2000/

###
POST http://localhost:2000/api

###
GET http://localhost:2000/article

###
POST http://localhost:2000/article
Content-Type: application/json

{
    "name": "Seba",
    "email": "sparra@gmail.com"
}

###
DELETE  http://localhost:2000/article/t3NGycPxLgDW28VgLqIx0

###
PATCH  http://localhost:2000/article/M2iIxanrP9PvlNIFCP3Cg
Content-Type: application/json

{
"name": "PEPITO"
    
}
### Save a url
POST http://localhost:2000/url
Content-Type: application/json

{
    "link": "http://www.google.com"
}
### Route doesnt exists
GET http://localhost:2000/route/that/does/not/exists

###